### ISSUE TITLE
[bug]: Vaultwarden sends emails over clearnet rather than Tor

### ISSUE THREAD

**Issue by 501st-alpha1** [Start9Labs/vaultwarden-startos#45]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Pop OS

### Browser

Firefox

### Browser Version

102.0.1

### Current Behavior

I recently was updating the SMTP Email Settings for my Vaultwarden install, and while troubleshooting another issue, I noticed in the logs of my mail server that Vaultwarden was connecting directly from my public IP, rather than through Tor.  Is this expected?  It's not a big deal in my case, since I also run my email server, but it would be nice if the connection could happen over Tor.

### Expected Behavior

My first choice would be for Vaultwarden to send any emails over a Tor connection (or at least optionally do so), but if that is not easy / feasible, this should probably be mentioned in the documentation somewhere, so that a Start9 user doesn't accidentally expose their home IP address.

### Steps to Reproduce

While watching logs of your mail server, use the "Send test email" button in the Vaultwarden admin portal; logs will show connection from public IP the Start9 device is connected to, rather than a random Tor public IP.

**Comment by gStart9** [comment]
While I like your proposed feature and agree with the sentiment, it's not worth the developing because:

1) Most tor exit nodes block outgoing SMTP port 25 anyway, and even if you do find a tor exit node that doesn't
2) Most mail servers' will outright block connections from known tor exits, because most mail servers' spam filters processes subscribe to IP block lists from known spam relays, and any tor exit that allows SMTP connections will make its way to the abuse lists very quickly

Until we get VPN or IP-fronting functionality in StartOS (some form(s) of which are due in v0.4.0), your best bet if you want to proxy your SMTP connections is to use a network-wide VPN if your router supports it.

**Comment by 501st-alpha1** [comment]
To clarify since you mentioned port 25, I was talking about using authenticated email submission (i.e. port 465 or 587 by default), not unauthenticated transfer over port 25.

My use case is I enter a username/hostname/port on the Vaultwarden admin page (here `<mydomain>.com`, but it could easily be e.g. `gmail.com` or `protonmail.com`), *and* I enter my password, so Vaultwarden will authenticate as the given user in order to send emails.  (And I know this works, because I have my mail server configured to reject any emails from unauthenticated users.)

I can't speak to whether mail servers will block even authenticated connections from known Tor exits, but unfortunately it wouldn't surprise me if that were true.  I expect there would be *some* exceptions to this rule; in particular Proton is very Tor-friendly.

If this is still a "won't fix" that is okay, it may still not be worth the effort.  But if that is the case, can this be mentioned in the docs somewhere so that other Start9 users don't expose their home IP to their mail server without realizing it?  (If you'd like to point me to the most appropriate place to include such a warning, I'd be happy to open a PR for that myself.)

**Comment by gStart9** [comment]
I don't think it's necessarily a "won't fix" -- I think we all agree you should be able to hide your real public IP.

Tor is going to be rejected from many (maybe most, but you're right, not all) smtp servers (even the authenticated, which can be done and was done on port 25 in the past -- the port just got so blocked they actually had to assign authenticated SMTP to a different port to even make it viable due to all the blocking ISPs and service providers have done).

That leaves a VPN or unix-shell-proxied traffic options, which is not (yet) built in to StartOS.  We're already planning on such solutions, but our VPN solution is so not done that it's not even currently started.  We have a long way to go to v0.4.0 but most such features are slated for that release.  v0.3.5 was finally released today which largely cleared our plate and laid the groundwork for v0.4.0.  So, only patience is required (unless you can help us code it).
